language: perl
perl:
  - "5.19"
  - "5.18.1_thr"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8.9"
  - "5.8.3"
before_install:
  - "source devel.travis/travis-perlbrew"
  - "perlbrew install-cpanm -f"
  - "perl -V"
install:
  - cpanm "Exporter::Tiny" "Scope::Guard" "Test::Fatal" "Test::More" "Test::Requires"
  - cpanm -n "Moo" "Moose"
script:
  - "HARNESS_IS_VERBOSE=1 prove -Ilib t"
